[package]
name = "chip8emu"
version = "0.1.0"
authors = ["Grant Wade <grant.wade@meridiansky.co>"]
edition = "2018"
license-file = "LICENSE"
keywords = ["emulator", "library"]
publish = false

[lib]
crate-type = ["dylib", "rlib"]
path = "src/system.rs"
doc = true


[dependencies]
rand = "0.7.3"
